name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Hello World
        run: |
          HELLO="WORLD"
          echo "$HELLO"
