name: christianfei-devblog build
on: [push]
jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        with:
          ref: refs/heads/master
      - name: install
        run: |
          npm install
      - name: build
        run: |
          npm run build
      - name: start server
        run: |
           npm start &
      - name: rss validation
        run: |
          npx feed-validator  http://127.0.0.1:8080/rss.xml
      - name: uat
        uses: cypress-io/github-action@v1
      - name: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          npm run deploy-with-assets
      - name: purge
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          CF_ZONE: ${{ secrets.CF_ZONE }}
          CF_DOMAIN: ${{ secrets.CF_DOMAIN }}
        run: |
          npm run purge
      - uses: christian-fei/github-action-send-telegram-message@master
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
        with:
          message: 'Deployed to https://cri.dev'
